FROM ubuntu:20.04

# Set non-interactive frontend for debconf
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages
RUN apt-get update && \
    apt-get install -y \
    curl \
    gnupg \
    lsb-release \
    && rm -rf /var/lib/apt/lists/*

# Add the ROS repository
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

# Add the ROS key
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -

# Update package list and install ROS
RUN apt-get update && \
    apt-get install -y ros-noetic-desktop-full && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Environment setup
RUN echo "source /opt/ros/noetic/setup.bash" >> /etc/bash.bashrc
RUN echo 'export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/root/freenect2/lib"' >> /etc/bash.bashrc
RUN echo 'export LD_LIBRARY_PATH="/opt/ros/noetic/lib:$LD_LIBRARY_PATH"' >> /etc/bash.bashrc

# Install additional ROS dependencies and other necessary libraries
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    nano \
    python3-pip \
    python3-rosdep \
    python3-rosinstall \
    python3-rosinstall-generator \
    python3-wstool \
    sudo \
    terminator \
    libusb-1.0-0-dev \
    libjpeg-turbo8 \
    libglfw3-dev \
    cmake \
    pkg-config \
    libturbojpeg0-dev \
    libgl1-mesa-dev \
    libopenni2-dev \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip and install specific numpy version and Kinect2 dependencies
RUN pip3 install --upgrade pip && \
    pip3 install numpy==1.24.4 opencv-python

# Clone and build libfreenect2
RUN git clone https://github.com/OpenKinect/libfreenect2.git /libfreenect2 && \
    cd /libfreenect2 && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/freenect2 && \
    make && \
    make install

# Copy udev rules for Kinect2
RUN sudo cp /libfreenect2/platform/linux/udev/90-kinect2.rules /etc/udev/rules.d/

# Copy pylibfreenect2 wheel and ros_publisher.py
COPY pylibfreenect2-0.1.4-cp38-cp38-linux_x86_64.whl /root/
COPY ros_publisher.py /root/

# Install pylibfreenect2 wheel
RUN pip3 install /root/pylibfreenect2-0.1.4-cp38-cp38-linux_x86_64.whl

# Initialize rosdep
RUN rosdep init && \
    rosdep update

# Set the entrypoint to bash to source the ROS setup file
ENTRYPOINT ["/bin/bash"]
